/**
 * The exact Harness Workspace surfaces `/worktrees` consumes, and nothing else.
 *
 * One seam answers everything the feature needs:
 *
 * ```
 * ctx.get('workspaceRegistry')   the durable records over canonical working
 *                                directories, their header-validated Session
 *                                membership, and the one authoritative route
 *                                that registers a directory
 * ```
 *
 * Written out narrowly rather than depended on as a whole service, for the
 * reason `connect/harness.ts` and `plugins/harness.ts` both give: naming the
 * calls one view makes is more legible than importing a service, and the
 * narrow view takes plain strings where the real registry takes branded ones,
 * which is what keeps every import here TYPE-ONLY. `@deepseek-ai/dsh-workspace`
 * is a real dependency because this bundle's `cordis.patch.yml` inserts its
 * row — availability is a shipped package; the CAPABILITY is what a
 * composition may drop — and the assignment in {@link worktreesSeams} checks
 * this view against the real service on every build, because the package
 * augments `Context` with its own type.
 *
 * The registry is optional in exactly the way `ctx.authorization` is: a
 * profile that omits the row still starts, and `/worktrees` reports that this
 * profile mounts no Workspace registry instead of falling back to a list of
 * directories dshline scanned for itself. There is no fallback anywhere in
 * this feature — a second account of "which working directories exist" would
 * be a second authority to disagree with, and neither the sessions tree nor
 * `git worktree list` is the authority Harness publishes.
 *
 * What this file deliberately does NOT declare is every method the real
 * registry has. `delete`, `insertBefore`, `insertSessionBefore`,
 * `detachSession`, `setTitle`, and `archiveSession` are all callable and all
 * absent here, because this is the set of surfaces this frontend CONSUMES
 * (rule 15): declaring a destructive or reordering one it never calls would
 * make every test double implement a path nothing exercises, while reading as
 * though `/worktrees` can delete a workspace or hide a session. Add one in the
 * same change that first offers it.
 * @module dshline/worktrees/harness
 */

import type { Context } from '@deepseek-ai/cordis'
import type { SessionId } from '@deepseek-ai/dsh-session'
// The `workspaceRegistry` Context augmentation, which is what makes the
// assignment in `worktreesSeams` a real check rather than a free narrowing.
// Type-only: nothing here imports a value from the package.
import type {} from '@deepseek-ai/dsh-workspace'

/**
 * One Harness Workspace as `/worktrees` reads it.
 *
 * `id` is a plain string here where the registry brands it `WorkspaceId`: this
 * frontend only ever hands an id back to the same registry that produced it,
 * so the brand buys nothing and importing it would buy a runtime dependency.
 */
export interface WorkspaceEntry {
  /** Stable record id, generated by Harness and never the path. */
  readonly id: string
  /**
   * The canonical directory this workspace owns.
   *
   * Harness's own `fs.realpath` result, taken at create time and never
   * rewritten afterwards. It is the authority for both the path a row shows
   * and the exact `cwd` a session query is filtered on, which is why nothing
   * in dshline normalizes, joins, or re-resolves it.
   */
  readonly path: string
  /** Display title; Harness defaults it to the path's basename. */
  readonly title: string
  /**
   * Sessions Harness accounts to this workspace, newest attachment first.
   *
   * Already filtered by the registry's own canonical-cwd header index, so a
   * member whose header cwd no longer resolves to {@link path} is absent.
   * Presentation reads its LENGTH only: the session rows themselves come from
   * `ctx.sessionQuery` filtered on the same exact cwd, which is the authority
   * `/sessions` already uses, rather than from a second corpus assembled out
   * of these ids.
   */
  readonly sessionIds: readonly SessionId[]
  /**
   * Prepend one session to this workspace's account, durably.
   *
   * Harness validates it: the session's stored header cwd must resolve to an
   * existing directory equal to {@link path}, so an unknown id or a session
   * created somewhere else rejects without writing. Idempotent for an id the
   * account already holds.
   * @param sessionId - the session to record.
   * @returns resolution after durability.
   */
  attachSession(sessionId: SessionId): Promise<void>
  /**
   * Live, uncached directory check.
   *
   * Read for the ONE workspace a reader opened, never per row: it is an
   * `fs.stat` per call, and a list that showed it would take one stat per row
   * every time the cursor moved. A missing directory never mutates the record
   * — the folder may only have been moved — so this is presentation, not a
   * lifecycle fact.
   * @returns `'ok'` when the directory exists, `'missing-dir'` otherwise.
   */
  status(): Promise<'ok' | 'missing-dir'>
}

/** The `ctx.workspaceRegistry` surface `/worktrees` reads and writes through. */
export interface WorkspaceRegistryReads {
  /**
   * Every known workspace, in Harness's own durable registry order.
   *
   * Synchronous and performs no persistence read: the entities and the order
   * are already resolved by the time the service is active.
   * @returns a fresh ordered array.
   */
  list(): WorkspaceEntry[]
  /**
   * Look up one workspace by the id a row carries.
   * @param id - the workspace id.
   * @returns the workspace, or undefined when the registry no longer holds it.
   */
  get(id: string): WorkspaceEntry | undefined
  /**
   * Resolve the workspace owning a directory, without creating one.
   *
   * The authoritative answer to "is the directory this window is rooted in a
   * known Workspace" — it canonicalizes through `fs.realpath`, which is the
   * uniqueness canon dshline must not reimplement. Rejects when the path does
   * not resolve.
   * @param path - an existing directory in any spelling.
   * @returns the owning workspace, or undefined for an unowned directory.
   */
  resolveByPath(path: string): Promise<WorkspaceEntry | undefined>
  /**
   * Register a directory as a Workspace, or return the one that already owns it.
   *
   * The single route Harness publishes for adding a workspace, and idempotent
   * per canonical path: a repeated call returns the existing record without
   * changing its title. Upstream's own Workspace controller offers exactly
   * this as a human command (`resolveByPath`, then `create`), which is why
   * offering it here is presentation of a Harness control rather than dshline
   * inventing a lifecycle. The optional `title` parameter is deliberately not
   * declared: upstream records that it has no production caller left and
   * proposes deleting it, and the basename Harness derives is the title a
   * terminal would have supplied anyway.
   * @param path - an existing directory to own.
   * @returns the existing or newly durable workspace.
   */
  create(path: string): Promise<WorkspaceEntry>
}

/** Which optional seams this deployment mounts for `/worktrees`. */
export interface WorktreeSeams {
  /** The Workspace registry, or undefined in a profile without the row. */
  readonly workspaceRegistry: WorkspaceRegistryReads | undefined
}

/**
 * Read the Workspace seam off a context, without asserting it is mounted.
 *
 * `ctx.get` answers `undefined` for an unmounted service, and
 * `@deepseek-ai/dsh-workspace` augments `Context` with the real service type —
 * so the annotated assignment below is a genuine conformance check of
 * {@link WorkspaceRegistryReads} against `WorkspaceRegistry`, with no cast in
 * either direction.
 * @param ctx - context carrying (or not carrying) the registry.
 * @returns the seam found.
 */
export function worktreesSeams(ctx: Context): WorktreeSeams {
  const workspaceRegistry: WorkspaceRegistryReads | undefined = ctx.get('workspaceRegistry')
  return { workspaceRegistry }
}

/** What recording a fresh session's workspace membership resolved to. */
export type MembershipOutcome =
  /** Harness accepted and durably recorded the membership. */
  | { readonly kind: 'attached' }
  /** This profile mounts no Workspace registry, so there was nothing to record. */
  | { readonly kind: 'unavailable' }
  /** The registry no longer holds the workspace the transition named. */
  | { readonly kind: 'unknown' }
  /** Harness refused; the message is its own and is untrusted. */
  | { readonly kind: 'failed'; readonly message: string }

/**
 * Record a freshly created session's membership of the workspace it was
 * started from.
 *
 * Called only AFTER `ctx.agents.create` succeeded, which is the ordering
 * Harness's own session controller uses: resolve the Workspace, create the
 * Session with `cwd = workspace.path`, then `workspace.attachSession(id)`. A
 * failed creation must not leave phantom membership behind, and a failed
 * ATTACH must not destroy a session that was created exactly as asked — so
 * this reports the failure and nothing else. Upstream makes the same choice:
 * its controller raises `session/workspace-attach-failed` naming both ids and
 * keeps the session.
 * @param ctx - context that may carry the registry.
 * @param workspaceId - the workspace the transition was started from.
 * @param sessionId - the session Harness just created.
 * @returns what the registry did, including when it could not.
 */
export async function recordWorkspaceMembership(
  ctx: Context,
  workspaceId: string,
  sessionId: SessionId,
): Promise<MembershipOutcome> {
  const registry = worktreesSeams(ctx).workspaceRegistry
  if (registry === undefined) return { kind: 'unavailable' }
  const workspace = registry.get(workspaceId)
  if (workspace === undefined) return { kind: 'unknown' }
  try {
    await workspace.attachSession(sessionId)
    return { kind: 'attached' }
  } catch (error: unknown) {
    return { kind: 'failed', message: error instanceof Error ? error.message : String(error) }
  }
}
